INSERT INTO `news` (`id`, `gamename`, `title`, `content`, `source`, `date`) VALUES
(1, 'Hades', 'Hades: v1.0 Has Arrived!!', 'After two years in early access, the highly anticipated game Hades has finally been released in its 1.0 version. Developed by Supergiant Games, Hades has already gained a massive following for its captivating storyline, stunning graphics, and innovative gameplay mechanics.', 'https://store.steampowered.com/news/app/1145360/view/2908719181633108409', '2020-09-18'),

(2, 'Hades', 'Hades: Nominated for Game of the Year!', 'Hades wins game of the year with its captivating story, stunning world-building, and polished gameplay mechanics. Supergiant Games should be proud of their achievement.', 'https://store.steampowered.com/news/app/1145360/view/4137084313616844005', '2020-12-22'),

(3, 'Portal 2', 'portal 2 rtx remake', 'nvidia has announced that they will remake portal 2 with rtx to show off the capabilities of their graphics card', 'https://store.steampowered.com/news/app/2012840/view/3620361554183195575', '2022-12-08'),

(4, 'Hades', 'Hades II: Coming to Steam Early Access!', 'Like its predecessor, Hades II will be available in Early Access here on Steam for some time leading up to its full v1.0 launch. Add Hades II to your wishlist for a handy reminder when the time comes', 'https://store.steampowered.com/news/app/1145350/view/3628242853594657531', '2022-12-08'),

(5, 'Counter-Strike: Global Offensive', 'Counter-Strike: Global Offensive is now available on Steam!', 'CS:GO expands on the classic team-based action gameplay that Counter-Strike pioneered. Featuring an arsenal of over 45 weapons, loads of maps, new game modes, new visuals, leaderboards, and over 165 Steam Achievements.', 'https://store.steampowered.com/news/app/730/view/2913221511623967917', '2012-08-22'),

(6, 'Counter-Strike: Global Offensive', 'ARMS DEAL UPDATE', 'Today marks the launch of the Arms Deal update for Counter-Strike: Global Offensive, which introduces an all-new economy system to the game. Players can now buy, sell, and trade in-game weapon skins, creating a bustling marketplace for rare and coveted skins.', 'https://store.steampowered.com/oldnews/11265', '2013-08-14'),

(7, 'Counter-Strike: Global Offensive', 'Play Operation Bloodhound!', 'It’s that magic time where spring prepares to give way to summer; a time for fun in the sun, vacations, friends, and of course… a brand new operation for CSGO! New modes, campaigns, and bragging rights await you… welcome to Operation Bloodhound.', 'https://store.steampowered.com/news/app/730/view/2913221511623966301', '2015-05-29'),

(8, 'Counter-Strike: Global Offensive', 'Operation Shattered Web', 'Introducing Operation Shattered Web. For the first time in CS:GO, bring your favorite character into battle with all-new equippable agents. Earn rewards featuring the new agents, all-new weapon collections, stickers, graffiti, and more through a new battle pass format. Complete weekly Operation Missions in various game modes including Co-op Guardian and a new Co-op Strike Mission!', 'https://store.steampowered.com/news/app/730/view/1604899184801773232', '2019-10-19'),

(9, 'Counter-Strike: Global Offensive', 'CS:GO has been nominated for the "Labor of Love" Steam Award!', 'The Steam Community has nominated CS:GO for the "Labor of Love" Steam Award, awarded to a previously released game which continues to receive updates.', 'https://store.steampowered.com/news/app/730/view/5315901521584470331', '2020-12-22'),

(10, 'Counter-Strike: Global Offensive', 'The Next Era of Counter-Strike', 'Counter-Strike 2 is the largest technical leap forward in Counter-Strike’s history, ensuring new features and updates for years to come.', 'https://store.steampowered.com/news/app/730/view/3716071937633222892', '2023-03-22')